services:
  web:
    container_name: web
    image: yuniyakim/web-editor:query
    ports:
      - "5000:5000"
    depends_on:
      - gateway
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    networks:
      - network-services
  gateway:
    container_name: gateway
    image: docker.pkg.github.com/real-net/web-editor-backend/gateway:query
    ports:
      - "8000:80"
    depends_on:
      - repo
      - auth
    networks:
      - network-services
  auth:
    container_name: auth
    image: docker.pkg.github.com/real-net/web-editor-backend/auth:query
    ports:
      - "8002:80"
    volumes:
      - type: bind
        source: ./Auth/users.db
        target: /users.db
    networks:
      - network-services
  repo:
    container_name: repo
    image: docker.pkg.github.com/real-net/web-editor-backend/repo:query
    ports:
      - "8004:80"
#    volumes:
#      - type: bind
#        source: ./Repo/serialized/
#        target: /serialized/
    networks:
      - network-services
  storage:
    container_name: storage
    image: docker.pkg.github.com/real-net/web-editor-backend/storage:query
    ports:
      - "8006:80"
#    volumes:
#      - type: bind
#        source: ./Storage/StorageDB.db
#        target: /StorageDB.db
    networks:
      - network-services
  generator:
    container_name: test
    image: docker.pkg.github.com/real-net/web-editor-backend/generator:query
    ports:
      - "8008:80"
    networks:
      - network-services
#  test:
#    container_name: test
#    image: docker.pkg.github.com/real-net/web-editor-backend/test:query
#    ports:
#      - "8099:80"
#    networks:
#      - network-services
networks:
  network-services:
    driver: bridge
